# Generated by Django 4.2.6 on 2024-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_contactus_alter_suggestion_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
