# Generated by Django 4.2.6 on 2024-02-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('programme', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('cgpa', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.student')),
            ],
        ),
    ]
