# Generated by Django 4.2.6 on 2024-02-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0005_remove_student_id_remove_student_marks_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='department',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='programme',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='two.student'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.student')),
            ],
        ),
    ]
