# Generated by Django 4.2.6 on 2024-02-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0006_alter_studentinfo_cgpa_alter_studentinfo_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
