# Generated by Django 4.2.6 on 2024-02-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0007_rename_subjects_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='marks',
            new_name='mark',
        ),
    ]
