# Generated by Django 4.2.6 on 2024-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0008_rename_marks_subject_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegGpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
