# Generated by Django 4.2.6 on 2024-02-16 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0009_reggpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reggpa',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
